version: '3.8'

services:

  frontend:
    build: ./example-frontend/
    ports:
      - 5000:5000
    container_name: frontd

  backend:
    build: ./example-backend/
    ports: 
      - 8080:8080
    container_name: backd
    
    #environment:
    # - REDIS_HOST=redis
    # depends_on:
    # - redis

      #redis:
      #image: redis
      #container_name: redis
